pipeline {
    agent any

    stages {

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Git Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/pradeepinfra/DevOps-24-09-2025.git'
            }
        }

        stage('Build') {
            steps {
                dir('Jenkins/java-application') {
                    sh 'mvn clean'
                }
            }
        }

        stage('Compile') {
            steps {
                dir('Jenkins/java-application') {
                    sh 'mvn compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Jenkins/java-application') {
                    sh 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('Jenkins/java-application') {
                    sh 'mvn package'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('Jenkins/java-application') {
                    sh 'docker build -t java-jenkins-docker:latest .'
                }
            }
        }

        stage('Docker Tag') {
            steps {
                sh 'docker tag java-jenkins-docker:latest infravyom/java-app:v1'
            }
        }

        stage('Docker Login (Hardcoded)') {
            steps {
                sh 'docker login -u infravyom -p Navya@9553'
            }
        }

        stage('Docker Push') {
            steps {
                sh 'docker push infravyom/java-app:v1'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Check Jenkins logs.'
        }
    }
}
